- name: Create log directory
  ansible.builtin.file:
    path: "{{ _log_dir }}"
    state: directory

- name: Overwrite kernel vfio-pci.ids
  ansible.builtin.file:
    path: "{{ log_blacklist }}"
    state: absent
  when: overwrite_blacklist

- include_tasks: '{{ ansible_os_family }}/main.yml'
