- name: Update grub
  ansible.builtin.shell: grub2-mkconfig -o /etc/grub2-efi.cfg
  become: true

- name: Reboot node
  ansible.builtin.reboot:
  when: not ansible_connection == 'local'
  become: true

- name: Reboot
  debug:
    msg: "{{'You must reboot manually! As you are setting up localhost' if ansible_connection == 'local' else 'Rebooting ...' }}"
  changed_when: true
  notify: Reboot node

- name: rpm-ostree initramfs # perform a dracut to make sure the initramfs has the Kernel module loaded
  ansible.builtin.shell: >
    rpm-ostree initramfs
    --enable
    --arg="--add-drivers"
    --arg="vfio-pci"
  become: true
