---
- name: Replace 
  ansible.builtin.replace:
    path: /etc/default/grub
    before: 'GRUB_CMDLINE_LINUX'
    regexp: 'quiet splash"$'
    replace: 'quiet splash {{ ignore_msrs }}vfio-pci.ids={{ vfio_pci_string }}"'
  become: true
  notify: Debian Update grub