- debug:
    msg: Detect Graphics Cards

- name: Get a GPU
  get_gpu:
    audio: true
  register: gpu

- name: Setting host facts using complex arguments
  ansible.builtin.set_fact:
    vfio_pci_string: "{{ gpu.pci_string }}"

- name: dump test output
  debug:
    msg: "{{ gpu }}"
    # msg: '{{ gpu.pci_string }} {{gpu.gpu_type}} {{gpu.blacklist_driver}}'
  when: debug

# from: https://www.heiko-sieger.info/blacklisting-graphics-driver/
