---

- name: check if storage pool is defined
  stat:
    path: '/etc/libvirt/storage/os.xml'
  register: pool_definition
  become: true

- import_tasks: remove-libvirt-pool.yml
  when: pool_definition.stat.exists == True
