---
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/virtualization_administration_guide/delete-lvm-storage-pool-virsh

- name: 1 Destroy pool
  become: true
  command: 'virsh pool-destroy {{item}}'
  with_items:
  - os

- name: 2 delete pool
  become: true
  command: 'virsh pool-delete {{item}}'
  with_items:
  - os


- name: 3 undefine pool
  become: true
  command: 'virsh pool-undefine {{item}}'
  with_items:
  - os

- name: Remove pool xml
  file:
    path:  '/etc/libvirt/storage/{{item}}.xml'
    state: absent
  with_items:
  - os

- name: Remove pool xml
  file:
    path:  '/etc/libvirt/storage/autostart/{{item}}.xml'
    state: absent
  with_items:
  - os
