---
- name: Todo - Use Autodetection instead!
  ansible.builtin.set_fact:
    existing_kernel_options: "quiet splash"

# Test:
# Uses clever quotes and regex $ to make idempotent!
- name: Enable iommu in grub kernel option
  ansible.builtin.replace:
    path: /etc/default/grub
    before: 'GRUB_CMDLINE_LINUX'
    regexp: '"{{ existing_kernel_options }}"$'
    replace: '"quiet splash intel_iommu=on kvm.ignore_msrs=1 vfio-pci.ids=1002:73ff,1002:ab28"'
  become: true
  notify: Debian Update grub

# Slightly different from Ubuntu!
# `GRUB_CMDLINE_LINUX` instead
# - name: ZorinOS - Enable iommu in grub kernel option
#   ansible.builtin.replace:
#     path: /etc/default/grub
#     before: 'GRUB_CMDLINE_LINUX="'
#     regexp: '{{ existing_kernel_options }}"$'
#     replace: 'intel_iommu=on {{ existing_kernel_options }}"'
#   become: true
#   notify: Debian Update grub