---
#https://en.wikipedia.org/wiki/Zorin_OS
#https://distrowatch.com/table.php?distribution=zorin


# Slightly different from Ubuntu!
# Has to use the second field: `GRUB_CMDLINE_LINUX=`
# - name: ZorinOS - Enable iommu in grub kernel option
#   ansible.builtin.replace:
#     path: /etc/default/grub
#     before: 'GRUB_CMDLINE_LINUX="'
#     regexp: '{{ existing_kernel_options }}"$'
#     replace: 'intel_iommu=on {{ existing_kernel_options }}"'
#   become: true
#   notify: Debian Update grub


# Test:
# Uses clever quotes and regex $ to make idempotent!
- name: Enable iommu in grub kernel option
  ansible.builtin.replace:
    path: /etc/default/grub
    before: 'GRUB_CMDLINE_LINUX'
    regexp: '"{{ existing_kernel_options }}"$'
    replace: '"quiet splash intel_iommu=on kvm.ignore_msrs=1 vfio-pci.ids=1002:73ff,1002:ab28"'
  become: true
  notify: Debian Update grub

