- name: Setup VFIO on node
  # hosts: localhost
  hosts: node
  vars:
    ansible_become_password: u
    optional_packages: true
  roles:
    - Get hardware/GPU
    # - Get hardware/HDMI Catpure Card
    - VFIO
